# -*- coding= utf-8 -*-

OBJ_TYPE = {
    b'BRDG'     : 'obj_bridge'      ,
    b'BUIL'     : 'obj_building'    ,
    b'CCAR'     : 'obj_citycar'     ,
    b'CRSS'     : 'obj_crossing'    ,
    b'CURS'     : 'obj_cursor'      ,
    b'FACT'     : 'obj_factory'     ,
    b'FFIE'     : 'obj_ffield'      ,
    b'FFCL'     : 'obj_ffldclass'   ,
    b'FIEL'     : 'obj_field'       ,
    b'FPRO'     : 'obj_fproduct'    ,
    b'FSMO'     : 'obj_fsmoke'      ,
    b'FSUP'     : 'obj_fsupplier'   ,
    b'GOOD'     : 'obj_good'        ,
    b'GRND'     : 'obj_ground'      ,
    b'GOBJ'     : 'obj_groundobj'   ,
    b'IMG\x00'  : 'obj_image'       ,
    b'IMG1'     : 'obj_imagelist'   ,
    b'IMG2'     : 'obj_imagelist'   ,
    b'MENU'     : 'obj_menu'        ,
    b'MISC'     : 'obj_miscimages'  ,
    b'PASS'     : 'obj_pedestrian'  ,
    b'SIGN'     : 'obj_roadsign'    ,
    b'ROOT'     : 'obj_root'        ,
    b'SMOK'     : 'obj_smoke'       ,
    b'SOUN'     : 'obj_sound'       ,
    b'SYMB'     : 'obj_symbol'      ,
    b'TEXT'     : 'obj_text'        ,
    b'TILE'     : 'obj_tile'        ,
    b'TREE'     : 'obj_tree'        ,
    b'TUNL'     : 'obj_tunnel'      ,
    b'VHCL'     : 'obj_vehicle'     ,
    b'WAY\x00'  : 'obj_way'         ,
    b'WYOB'     : 'obj_way'         ,
    b'XREF'     : 'obj_xref'
}
