# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(708, 463)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.folderlist = QtWidgets.QListView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folderlist.sizePolicy().hasHeightForWidth())
        self.folderlist.setSizePolicy(sizePolicy)
        self.folderlist.setAcceptDrops(True)
        self.folderlist.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.folderlist.setDragEnabled(False)
        self.folderlist.setObjectName("folderlist")
        self.gridLayout.addWidget(self.folderlist, 1, 0, 5, 1)
        self.paklist = QtWidgets.QTableView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paklist.sizePolicy().hasHeightForWidth())
        self.paklist.setSizePolicy(sizePolicy)
        self.paklist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.paklist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.paklist.setSortingEnabled(True)
        self.paklist.setCornerButtonEnabled(False)
        self.paklist.setObjectName("paklist")
        self.paklist.horizontalHeader().setDefaultSectionSize(250)
        self.paklist.verticalHeader().setDefaultSectionSize(25)
        self.gridLayout.addWidget(self.paklist, 1, 1, 3, 3)
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 6, 0, 1, 1)
        self.pakinfo = QtWidgets.QTableView(self.centralWidget)
        self.pakinfo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pakinfo.sizePolicy().hasHeightForWidth())
        self.pakinfo.setSizePolicy(sizePolicy)
        self.pakinfo.setObjectName("pakinfo")
        self.gridLayout.addWidget(self.pakinfo, 4, 1, 3, 2)
        self.ImgViewer = QtWidgets.QLabel(self.centralWidget)
        self.ImgViewer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImgViewer.sizePolicy().hasHeightForWidth())
        self.ImgViewer.setSizePolicy(sizePolicy)
        self.ImgViewer.setMaximumSize(QtCore.QSize(256, 256))
        self.ImgViewer.setAlignment(QtCore.Qt.AlignCenter)
        self.ImgViewer.setObjectName("ImgViewer")
        self.gridLayout.addWidget(self.ImgViewer, 4, 3, 3, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 708, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuHighlight_2 = QtWidgets.QMenu(self.menuView)
        self.menuHighlight_2.setObjectName("menuHighlight_2")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_pak_files = QtWidgets.QAction(MainWindow)
        self.actionOpen_pak_files.setEnabled(True)
        self.actionOpen_pak_files.setObjectName("actionOpen_pak_files")
        self.actionAdd_Simutrans_pak_folder = QtWidgets.QAction(MainWindow)
        self.actionAdd_Simutrans_pak_folder.setObjectName("actionAdd_Simutrans_pak_folder")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.action_None = QtWidgets.QAction(MainWindow)
        self.action_None.setCheckable(True)
        self.action_None.setObjectName("action_None")
        self.actionConflicting = QtWidgets.QAction(MainWindow)
        self.actionConflicting.setCheckable(True)
        self.actionConflicting.setObjectName("actionConflicting")
        self.actionDuplicating = QtWidgets.QAction(MainWindow)
        self.actionDuplicating.setCheckable(True)
        self.actionDuplicating.setObjectName("actionDuplicating")
        self.menuFile.addAction(self.actionAdd_Simutrans_pak_folder)
        self.menuFile.addAction(self.actionOpen_pak_files)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHighlight_2.addAction(self.action_None)
        self.menuHighlight_2.addAction(self.actionConflicting)
        self.menuHighlight_2.addAction(self.actionDuplicating)
        self.menuView.addAction(self.menuHighlight_2.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.folderlist, self.paklist)
        MainWindow.setTabOrder(self.paklist, self.pakinfo)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Suiterans"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHighlight_2.setTitle(_translate("MainWindow", "Highlight"))
        self.actionOpen_pak_files.setText(_translate("MainWindow", "Open .pak files"))
        self.actionAdd_Simutrans_pak_folder.setText(_translate("MainWindow", "Add Simutrans .pak folder"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_None.setText(_translate("MainWindow", "(None)"))
        self.actionConflicting.setText(_translate("MainWindow", "Conflicting"))
        self.actionDuplicating.setText(_translate("MainWindow", "Duplicating"))
